{% set name = "pyreadr" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1e5f001ad720dd507a98a577ce970f44becef9fb15fd4834c704be4abe72cad

build:
  number: 0
  skip: True  # [py<35]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - zlib
  run:
    - python
    - pandas
    - zlib

test:
  imports:
    - pyreadr
   
about:
  home: https://github.com/ofajardo/pyreadr
  license: AGPL
  license_family: AGPL
  license_file: LICENSE.txt
  summary: 'read R RData and Rds files into pandas data frames'
  description: |
    Python package to read and write R RData and Rds files into/from pandas dataframes. No R or other external dependencies required.
  doc_url: https://github.com/ofajardo/pyreadr
  dev_url: https://github.com/ofajardo/pyreadr

extra:
  recipe-maintainers:
    - ofajardo
