{% set name = "pyreadr" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b9e2a1da89044cf4daf8c9e03b95b6ceb9139f82c037cfb607e607243534b75

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - zlib
  run:
    - python
    - pandas
    - zlib

test:
  imports:
    - pyreadr

about:
  home: https://github.com/ofajardo/pyreadr
  license: AGPL
  license_family: AGPL
  license_file: LICENSE.txt
  summary: read R RData and Rds files into pandas data frames
  description: |
    Python package to read and write R RData and Rds files into/from pandas dataframes. No R or other external dependencies required.
  doc_url: https://github.com/ofajardo/pyreadr
  dev_url: https://github.com/ofajardo/pyreadr

extra:
  recipe-maintainers:
    - ofajardo
